plugins {
  id "java-library"
  id "com.vanniktech.maven.publish"
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(24)
  }
}

dependencies {
  api project(":json-logic-core")
  testImplementation libs.asm.tree
  testImplementation libs.asm.util
  testImplementation libs.junit.jupiter
  testRuntimeOnly libs.junit.platform.launcher
}
