plugins {
  id "java-library"
  id "com.vanniktech.maven.publish"
}

dependencies {
  api "com.google.code.gson:gson:2.14.0"
  testImplementation "org.junit.jupiter:junit-jupiter:5.14.4"
  testImplementation "org.junit.jupiter:junit-jupiter-params:5.14.4"
  testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}
