plugins {
  id "java"
}

dependencies {
  testImplementation project(":json-logic-java-core")
  testRuntimeOnly project(":json-logic-java-compiler-javac")
  testImplementation "com.google.code.gson:gson:2.14.0"
  testImplementation "org.junit.jupiter:junit-jupiter:5.14.4"
  testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}
