plugins {
  id "java"
}

dependencies {
  testImplementation project(":json-logic-core")
  testImplementation project(":json-logic-java-compiler-javac")
  testImplementation project(":json-logic-jep484")
  testImplementation libs.gson
  testImplementation libs.junit.jupiter
  testRuntimeOnly libs.junit.platform.launcher
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(24)
  }
}

tasks.withType(JavaCompile).configureEach {
  options.release = 24
}
